# WordPress Docker
version: '3.7'
services:
#Database
  db:
    image: mariadb:latest
    container_name: bethel-demo-db
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/home/ddb
    environment:
      MYSQL_DATABASE: wpdemo
      MYSQL_USER: wpdemo_user
      MYSQL_PASSWORD: BR3emm2
      MYSQL_ALLOW_EMPTY_PASSWORDS: 'no'
      MYSQL_ROOT_PASSWORD: BR3emm2
#Wordpress
  wordpress:
    image: wordpress:latest
    container_name: bethel-demo-wp
    restart: always
    depends_on: ['db']
    ports: ['8000:80']
    links: ['db:db']
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/home
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdemo
      WORDPRESS_DB_USER: wpdemo_user
      WORDPRESS_DB_PASSWORD: BR3emm2
#phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bethel-phpmyadmin
    restart: always
    depends_on: ['db']
    ports: ['12000:80']
    links: ['db:db']
    environment:
      PMA_HOST: db
      PMA_USER: wpdemo_user
      PMA_PASSWORD: BR3emm2
volumes:
  db_data: {}